### ISSUE TITLE
Creating a Default Value for a Missing Key

### ISSUE THREAD

**Issue by chrisjpowers** [groupon/params_deserializers#7]
I'm trying to create a default value for when a key is missing. I suspected that I could do this:

```ruby
class Foo < ParamsDeserializer
  attribute :bar

  def bar
    params_root["bar"] || "default"
  end
end

expect(Foo.new({}).deserialize()[:bar]).to eq("default")
```

However, this does not work because the `bar` method never runs because the `bar` key is missing from the input. This functionality is ensured by this spec, which makes it clear the behavior is desired:

https://github.com/chrisjpowers/params_deserializers/blob/master/spec/params_deserializers/params_deserializer_spec.rb#L396-L400

Is there a way to create a default value another way? Is this missing key behavior really desired behavior?

**Comment by jessepinho** [comment]
Hey @chrisjpowers!

By [default](https://github.com/chrisjpowers/params_deserializers/blob/master/lib/params_deserializers/attribute.rb#L38), keys will not be in the deserialized params if they're not in the original params. You can override this to make the key *always* be present using [the `present_if` key](https://github.com/chrisjpowers/params_deserializers#deciding-whether-a-key-should-be-present), though:

```ruby
class Foo < ParamsDeserializer
  attribute :bar, present_if: -> { true } # This will always be present now

  def bar
    params_root["bar"] || "default"
  end
end

expect(Foo.new({}).deserialize()[:bar]).to eq("default") # Should pass now
```

**Comment by chrisjpowers** [comment]
Ah, okay, that should work, thanks!
